name: Build and deploy Blazor WebAssembly to Azure Static Web App

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  APP_DIRECTORY: DartsScoreboard
  OUTPUT_LOCATION: wwwroot
  API_DIRECTORY: ''
  AZURE_STATIC_WEBAPP_NAME: darts-scoreboard

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web App

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish ${{ env.APP_DIRECTORY }} -c Release -o release

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.darts_scoreboard_SPN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ${{ env.APP_DIRECTORY }}
          api_location: ${{ env.API_DIRECTORY }}
          output_location: ${{ env.OUTPUT_LOCATION }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Environment

    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.darts_scoreboard_SPN }}
          action: close
          repo_token: ${{ secrets.GITHUB_TOKEN }}
